**SET UP NOTEBOOK**

In [2]:
import pandas as pd

df = pd.read_csv("train.csv")

cols = ["SalePrice", "GrLivArea", "OverallQual", "YearBuilt", "Neighborhood", "BedroomAbvGr"]
small = df[cols].copy()
small.head()

   SalePrice  GrLivArea  OverallQual  YearBuilt Neighborhood  BedroomAbvGr
0     208500       1710            7       2003      CollgCr             3
1     181500       1262            6       1976      Veenker             3
2     223500       1786            7       2001      CollgCr             3
3     140000       1717            7       1915      Crawfor             3
4     250000       2198            8       2000      NoRidge             4

**SELECT COLUMNS**

In [3]:
small["SalePrice"]   # one column
small[["SalePrice", "GrLivArea"]]  # two columns
small.loc[0]                       # one row, the first house
small.loc[0:2, ["SalePrice", "YearBuilt"]]  # rows 0 to 2, two columns

   SalePrice  YearBuilt
0     208500       2003
1     181500       1976
2     223500       2001

In [5]:
small[["Neighborhood", "YearBuilt"]].head()

  Neighborhood  YearBuilt
0      CollgCr       2003
1      Veenker       1976
2      CollgCr       2001
3      Crawfor       1915
4      NoRidge       2000

**FILTER ROWS**

In [6]:
big_homes = small[small["GrLivArea"] > 2000]
print(len(big_homes))
big_homes.head()

214

    SalePrice  GrLivArea  OverallQual  YearBuilt Neighborhood  BedroomAbvGr
4      250000       2198            8       2000      NoRidge             4
7      200000       2090            7       1973       NWAmes             3
11     345000       2324            9       2005      NridgHt             4
20     325300       2376            8       2005      NridgHt             4
35     309000       2452            8       2004      NridgHt             4

In [7]:
small[small["Neighborhood"] == "NoRidge"].head()

     SalePrice  GrLivArea  OverallQual  YearBuilt Neighborhood  BedroomAbvGr
4       250000       2198            8       2000      NoRidge             4
85      260000       2417            8       1991      NoRidge             4
226     290000       2520            7       1995      NoRidge             4
231     403000       2794            8       1995      NoRidge             4
272     290000       2270            8       1999      NoRidge             4

In [9]:
good_new = small[(small["YearBuilt"]  > 2000) & (small["OverallQual"] >= 8)]
print(len(good_new))
good_new.head()

159

    SalePrice  GrLivArea  OverallQual  YearBuilt Neighborhood  BedroomAbvGr
6      307000       1694            8       2004      Somerst             3
11     345000       2324            9       2005      NridgHt             4
20     325300       2376            8       2005      NridgHt             4
22     230000       1795            8       2002      CollgCr             3
25     256300       1600            8       2007      NridgHt             3

In [10]:
luxury_homes = small[(small["SalePrice"] > 400000) & (small["BedroomAbvGr"] >= 4)]
print(len(luxury_homes))
luxury_homes.head()

14

     SalePrice  GrLivArea  OverallQual  YearBuilt Neighborhood  BedroomAbvGr
185     475000       3608           10       1892      OldTown             4
231     403000       2794            8       1995      NoRidge             4
349     437154       2728            9       2005      NridgHt             4
496     430000       3228            8       1992      NoRidge             4
661     402000       2448            8       1994      NoRidge             4

**5 MOST EXPENSIVE**

In [11]:
small.sort_values("SalePrice", ascending = False).head(5)

      SalePrice  GrLivArea  OverallQual  YearBuilt Neighborhood  BedroomAbvGr
691      755000       4316           10       1994      NoRidge             4
1182     745000       4476           10       1996      NoRidge             4
1169     625000       3627           10       1995      NoRidge             4
898      611657       2364            9       2009      NridgHt             2
803      582933       2822            9       2008      NridgHt             4

**THE 5  CHEAPEST HOUSES**

In [12]:
small.sort_values("SalePrice")

      SalePrice  GrLivArea  OverallQual  YearBuilt Neighborhood  BedroomAbvGr
495       34900        720            4       1920       IDOTRR             2
916       35311        480            2       1949       IDOTRR             1
968       37900        968            3       1910      OldTown             2
533       39300        334            1       1946      BrkSide             1
30        40000       1317            4       1920       IDOTRR             3
...         ...        ...          ...        ...          ...           ...
803      582933       2822            9       2008      NridgHt             4
898      611657       2364            9       2009      NridgHt             2
1169     625000       3627           10       1995      NoRidge             4
1182     745000       4476           10       1996      NoRidge             4
691      755000       4316           10       1994      NoRidge             4

[1460 rows x 6 columns]

**SORT BY TWO COLUMNS**

In [13]:
small.sort_values(["OverallQual", "SalePrice"], ascending = [False, False]).head(5)

      SalePrice  GrLivArea  OverallQual  YearBuilt Neighborhood  BedroomAbvGr
691      755000       4316           10       1994      NoRidge             4
1182     745000       4476           10       1996      NoRidge             4
1169     625000       3627           10       1995      NoRidge             4
440      555000       2402           10       2008      NridgHt             2
185      475000       3608           10       1892      OldTown             4

**QUICK EXTREMES**

In [14]:
print(small["SalePrice"].max())
print(small["SalePrice"].min())
print(small["SalePrice"].mean())

755000
34900
180921.19589041095

In [15]:
small.sort_values(["GrLivArea", "SalePrice"], ascending = [False, False]).head(5)

      SalePrice  GrLivArea  OverallQual  YearBuilt Neighborhood  BedroomAbvGr
1298     160000       5642           10       2008      Edwards             3
523      184750       4676           10       2007      Edwards             3
1182     745000       4476           10       1996      NoRidge             4
691      755000       4316           10       1994      NoRidge             4
1169     625000       3627           10       1995      NoRidge             4