**SQLITE_3**

In [1]:
import sqlite3
import pandas as pd

df = pd.read_csv("train.csv")
conn = sqlite3.connect("housing.db")
df.to_sql("houses", conn, if_exists = "replace", index = False)

def q(sql):
  return pd.read_sql(sql, conn)

In [2]:
q("SELECT Neighborhood, SalePrice, YearBuilt FROM houses WHERE SalePrice > 300000")

    Neighborhood  SalePrice  YearBuilt
0        Somerst     307000       2004
1        NridgHt     345000       2005
2        NridgHt     325300       2005
3        NridgHt     306000       2007
4        NridgHt     309000       2004
..           ...        ...        ...
110      NoRidge     466500       2001
111      Gilbert     377500       2006
112      NoRidge     340000       1998
113      NridgHt     394617       2008
114      Somerst     310000       2008

[115 rows x 3 columns]

In [3]:
q("SELECT Neighborhood, SalePrice FROM houses WHERE Neighborhood = 'NoRidge' ORDER BY SalePrice DESC")

   Neighborhood  SalePrice
0       NoRidge     755000
1       NoRidge     745000
2       NoRidge     625000
3       NoRidge     466500
4       NoRidge     430000
5       NoRidge     410000
6       NoRidge     403000
7       NoRidge     402000
8       NoRidge     350000
9       NoRidge     348000
10      NoRidge     341000
11      NoRidge     340000
12      NoRidge     337000
13      NoRidge     336000
14      NoRidge     333168
15      NoRidge     325000
16      NoRidge     315750
17      NoRidge     315000
18      NoRidge     310000
19      NoRidge     302000
20      NoRidge     301500
21      NoRidge     290000
22      NoRidge     290000
23      NoRidge     290000
24      NoRidge     290000
25      NoRidge     285000
26      NoRidge     280000
27      NoRidge     271000
28      NoRidge     269790
29      NoRidge     268000
30      NoRidge     265000
31      NoRidge     262000
32      NoRidge     260400
33      NoRidge     260000
34      NoRidge     260000
35      NoRidge     258000
36      NoRidge     250000
37      NoRidge     248000
38      NoRidge     248000
39      NoRidge     221000
40      NoRidge     190000

In [4]:
q("SELECT Neighborhood, SalePrice, GrLivArea FROM houses WHERE GrLivArea > 3000 ORDER BY SalePrice")

   Neighborhood  SalePrice  GrLivArea
0       Edwards     160000       5642
1       Edwards     184750       4676
2         SWISU     197000       3082
3         SWISU     200000       3395
4       ClearCr     200500       3086
5         NAmes     235000       3112
6       OldTown     295000       3493
7       SawyerW     320000       3222
8       Crawfor     359100       3194
9       Crawfor     381000       3447
10      NoRidge     410000       3238
11      NoRidge     430000       3228
12      OldTown     475000       3608
13      NridgHt     485000       3140
14      StoneBr     538000       3279
15      NoRidge     625000       3627
16      NoRidge     745000       4476
17      NoRidge     755000       4316

*Location matters alongside size: even the cheapest NoRidge house (190,000) sold above the overall median (163,000), while the two largest houses, both in Edwards, were the cheapest of all houses over 3,000 sq ft.*

In [5]:
q("SELECT Neighborhood, SalePrice, BedroomAbvGr FROM houses WHERE SalePrice BETWEEN 150000 AND 200000 AND BedroomAbvGr = 3")

    Neighborhood  SalePrice  BedroomAbvGr
0        Veenker     181500             3
1         NWAmes     200000             3
2        SawyerW     159000             3
3         Sawyer     154000             3
4        CollgCr     179900             3
..           ...        ...           ...
266       NWAmes     197000             3
267      Crawfor     191000             3
268      CollgCr     179600             3
269      Mitchel     157900             3
270      Gilbert     175000             3

[271 rows x 3 columns]

In [6]:
q("SELECT Neighborhood, SalePrice FROM houses WHERE Neighborhood IN ('NoRidge', 'NridgHT', 'StoneBr') ORDER BY SalePrice DESC LIMIT 10")

  Neighborhood  SalePrice
0      NoRidge     755000
1      NoRidge     745000
2      NoRidge     625000
3      StoneBr     556581
4      StoneBr     538000
5      StoneBr     501837
6      NoRidge     466500
7      StoneBr     438780
8      NoRidge     430000
9      NoRidge     410000

In [7]:
q("SELECT Neighborhood, SalePrice FROM houses WHERE Neighborhood IN ('NoRidge', 'NridgHt', 'StoneBr') ORDER BY SalePrice DESC LIMIT 10")

  Neighborhood  SalePrice
0      NoRidge     755000
1      NoRidge     745000
2      NoRidge     625000
3      NridgHt     611657
4      NridgHt     582933
5      StoneBr     556581
6      NridgHt     555000
7      StoneBr     538000
8      StoneBr     501837
9      NridgHt     485000

In [8]:
q("SELECT DISTINCT Neighborhood FROM houses WHERE Neighborhood LIKE 'N%' ")

  Neighborhood
0      NoRidge
1       NWAmes
2      NridgHt
3        NAmes
4      NPkVill

In [9]:
q("SELECT COUNT (*) AS houses_with_no_garagge FROM houses WHERE GarageCars = 0")

   houses_with_no_garagge
0                      81

In [10]:
q("SELECT Neighborhood, SalePrice FROM houses ORDER BY SalePrice LIMIT 5")

  Neighborhood  SalePrice
0       IDOTRR      34900
1       IDOTRR      35311
2      OldTown      37900
3      BrkSide      39300
4       IDOTRR      40000

In [11]:
q("SELECT Neighborhood, SalePrice FROM houses WHERE SalePrice > 400000 AND Neighborhood != 'NoRidge' ORDER BY SalePrice DESC")

   Neighborhood  SalePrice
0       NridgHt     611657
1       NridgHt     582933
2       StoneBr     556581
3       NridgHt     555000
4       StoneBr     538000
5       StoneBr     501837
6       NridgHt     485000
7       OldTown     475000
8       NridgHt     465000
9       NridgHt     451950
10      NridgHt     446261
11      NridgHt     440000
12      StoneBr     438780
13      NridgHt     437154
14      NridgHt     426000
15      CollgCr     424870
16      Somerst     423000
17      NridgHt     415298
18      NridgHt     412500
19      NridgHt     402861

In [16]:
q("SELECT OverallQual, SalePrice, Neighborhood, YearBuilt FROM houses WHERE YearBuilt < 1950 AND OverallQual >=7 ORDER BY SalePrice DESC ")

    OverallQual  SalePrice Neighborhood  YearBuilt
0            10     475000      OldTown       1892
1             8     381000      Crawfor       1935
2             8     359100      Crawfor       1934
3            10     325000      OldTown       1893
4             8     315000      Crawfor       1932
5             7     311500      Crawfor       1939
6             7     295000      OldTown       1880
7             7     266500      Crawfor       1941
8             7     265979      OldTown       1880
9             7     250000      Crawfor       1936
10            7     244400      ClearCr       1940
11            8     235000        NAmes       1918
12            7     234000      Crawfor       1926
13            8     230000      Crawfor       1929
14            7     219500      Crawfor       1940
15            7     205000      BrkSide       1925
16            7     200100      Crawfor       1920
17            7     197000        SWISU       1920
18            7     189950      Crawfor       1918
19            7     184000      BrkSide       1925
20            7     178000      OldTown       1925
21            7     174500      Crawfor       1941
22            7     169500       IDOTRR       1931
23            8     168000      OldTown       1882
24            7     167500      BrkSide       1910
25            7     164000      Crawfor       1941
26            7     163000      OldTown       1914
27            8     161000      OldTown       1925
28            7     161000      OldTown       1928
29            7     159500      OldTown       1890
30            7     157000      OldTown       1920
31            7     155000        SWISU       1936
32            7     155000      OldTown       1915
33            7     149000      Crawfor       1931
34            7     145000        SWISU       1928
35            7     144000      OldTown       1916
36            7     143000      OldTown       1920
37            7     140000      Crawfor       1915
38            7     140000      OldTown       1921
39            7     139400       IDOTRR       1930
40            7     135000      OldTown       1946
41            7     132000      BrkSide       1929
42            7     129900      OldTown       1931
43            7     122000      OldTown       1910
44            8     122000      OldTown       1872
45            7     116900      OldTown       1926

*Among the 46 houses built before 1950 with a quality score of 7 or higher, 26 sold above the overall median (163,000). Most (35) are in OldTown and Crawfor, and Crawfor’s typical price (about 230,000) is well above OldTown’s (about 158,000), so location matters alongside quality.*